[package]
name = "randwall"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"


[profile.release]
opt-level = "z"
strip = true  # WE STRIPPING THE SYMBOLS WITH THIS ONE  ğŸ—£ï¸ğŸ—£ï¸ğŸ”¥ğŸ”¥ğŸ”¥
panic = "abort"
lto = true
